version: '3.3'
services:
  db:
    container_name: db
    image: postgres:13.6-alpine
    environment:
      POSTGRES_PASSWORD: napo
    ports:
      - 5432:5432
    volumes:
      - ./docker/psql/initdb.d:/docker-entrypoint-initdb.d
  backend:
    build: .
    ports:
      - 7000:7000
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=napo
      - PGDATABASE=napo
      - PGDPORT=5432
      - PORT=7000
    volumes:
      - .:/repo
